### Importamos librerias

In [30]:
# Tratamiento de datos
import pandas as pd

# Exploración de archivos
import sys
import os

# Funciones personalizadas
sys.path.append(os.path.abspath('../src'))
import sp_eda as se

### Para mostrar todas las columnas

In [31]:
pd.set_option('display.max_columns', None)

### Cargamos los conjuntos de datos desde un archivo CSV

In [32]:
df_sales = pd.read_csv('../data/raw/sales.csv', parse_dates=['SalesDate'])
df_customers = pd.read_csv('../data/raw/customers.csv')
df_products = pd.read_csv('../data/raw/products.csv', parse_dates=['ModifyDate'])
df_categories = pd.read_csv('../data/raw/categories.csv')
df_cities = pd.read_csv('../data/raw/cities.csv')
df_countries = pd.read_csv('../data/raw/countries.csv')

### Creamos el dataset unico

Todos los archivos están vinculados y se pueden combinar en un único conjunto de datos.

Relaciones de datos:
- 'sales' --> 'products' (ProductID), 'customers' (CustomerID)
- 'customers' --> 'cities' (CityID)
- 'cities' --> 'countries' (CountryID)
- 'products' --> 'categories' (CategoryID)

Antes de unir los conjuntos de datos verificamos la integridad de las claves primarias y foráneas antes de realizar las uniones:
- ProductID
- CustomerID
- CityID
- CountryID
- CategoryID

Del análisis preliminar sabemos que no hay valores nulos ni duplicados entre las claves.

In [33]:
se.claves_merge(df_sales, df_products,'ProductID')

 Clave: ProductID
1. Tipos de datos:
Dtype izquierda  : int64
Dtype derecha: int64
Tipos de datos coinciden!
2. Valores nulos:
Valores nulos en la izquierda: 0
Valores nulos en la derecha: 0
3. Unicidad en la tabla derecha:
Valores únicos: 452
Total filas   : 452
La clave es única (1:1 o N:1 relación)
4. Las claves de la izquierda que faltan en la derecha:
Faltan claves únicas: 0
Todas las claves coinciden

In [34]:
se.claves_merge(df_sales, df_customers,'CustomerID')

 Clave: CustomerID
1. Tipos de datos:
Dtype izquierda  : int64
Dtype derecha: int64
Tipos de datos coinciden!
2. Valores nulos:
Valores nulos en la izquierda: 0
Valores nulos en la derecha: 0
3. Unicidad en la tabla derecha:
Valores únicos: 98759
Total filas   : 98759
La clave es única (1:1 o N:1 relación)
4. Las claves de la izquierda que faltan en la derecha:
Faltan claves únicas: 0
Todas las claves coinciden

In [35]:
se.claves_merge(df_customers, df_cities,'CityID')

 Clave: CityID
1. Tipos de datos:
Dtype izquierda  : int64
Dtype derecha: int64
Tipos de datos coinciden!
2. Valores nulos:
Valores nulos en la izquierda: 0
Valores nulos en la derecha: 0
3. Unicidad en la tabla derecha:
Valores únicos: 96
Total filas   : 96
La clave es única (1:1 o N:1 relación)
4. Las claves de la izquierda que faltan en la derecha:
Faltan claves únicas: 0
Todas las claves coinciden

In [36]:
se.claves_merge(df_cities, df_countries,'CountryID')

 Clave: CountryID
1. Tipos de datos:
Dtype izquierda  : int64
Dtype derecha: int64
Tipos de datos coinciden!
2. Valores nulos:
Valores nulos en la izquierda: 0
Valores nulos en la derecha: 0
3. Unicidad en la tabla derecha:
Valores únicos: 206
Total filas   : 206
La clave es única (1:1 o N:1 relación)
4. Las claves de la izquierda que faltan en la derecha:
Faltan claves únicas: 0
Todas las claves coinciden

In [37]:
se.claves_merge(df_products, df_categories, 'CategoryID')

 Clave: CategoryID
1. Tipos de datos:
Dtype izquierda  : int64
Dtype derecha: int64
Tipos de datos coinciden!
2. Valores nulos:
Valores nulos en la izquierda: 0
Valores nulos en la derecha: 0
3. Unicidad en la tabla derecha:
Valores únicos: 11
Total filas   : 11
La clave es única (1:1 o N:1 relación)
4. Las claves de la izquierda que faltan en la derecha:
Faltan claves únicas: 0
Todas las claves coinciden

In [38]:
# Al verificar las claves no se encontraron inconsistencias estructurales significativas.
# Podemos realizar uniones de las tablas
df = df_sales.merge(df_products, how = 'left', on = 'ProductID')
df = df.merge(df_customers, how = 'left', on = 'CustomerID')
df = df.merge(df_cities, how = 'left', on = 'CityID')
df = df.merge(df_countries, how = 'left', on = 'CountryID')
df = df.merge(df_categories, how = 'left', on = 'CategoryID')

In [39]:
# Comprobamos el Dataframe unido:
df.head()

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber,ProductName,Price,CategoryID,Class,ModifyDate,Resistant,IsAllergic,VitalityDays,FirstName,MiddleInitial,LastName,CityID,Address,CityName,Zipcode,CountryID,CountryName,CountryCode,CategoryName
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,Vaccum Bag 10x13,44.2337,1,High,2018-01-06 22:26:53.580,Unknown,Unknown,41.0,Susan,V,Green,54,826 Rocky Second Freeway,Albuquerque,55358,32,United States,AR,Confections
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,Sardines,62.5460,8,Low,2017-12-03 21:41:12.420,Durable,False,90.0,Telly,W,Pollard,71,334 Cowley Street,Phoenix,84193,32,United States,AR,Grain
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,Crab - Imitation Flakes,79.0184,11,Medium,2017-08-19 07:18:29.890,Durable,True,0.0,Jon,K,Rangel,2,537 First St.,Buffalo,17420,32,United States,AR,Produce
3,4,8,73966,176,19,0.2,0.0,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,Smirnoff Green Apple Twist,81.3167,6,High,2017-08-27 17:08:59.840,Durable,True,90.0,Carol,V,Gilmore,45,41 Hague Way,Dallas,20151,32,United States,AR,Seafood
4,5,10,32653,310,9,0.0,0.0,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,Coffee - Dark Roast,79.9780,9,Low,2018-01-14 19:33:15.530,Weak,False,0.0,Terra,V,Carter,82,18 East Second Boulevard,Charlotte,39774,32,United States,AR,Poultry

### Eliminación las columnas

In [40]:
df.columns

Index(['SalesID', 'SalesPersonID', 'CustomerID', 'ProductID', 'Quantity',
       'Discount', 'TotalPrice', 'SalesDate', 'TransactionNumber',
       'ProductName', 'Price', 'CategoryID', 'Class', 'ModifyDate',
       'Resistant', 'IsAllergic', 'VitalityDays', 'FirstName', 'MiddleInitial',
       'LastName', 'CityID', 'Address', 'CityName', 'Zipcode', 'CountryID',
       'CountryName', 'CountryCode', 'CategoryName'],
      dtype='object')

In [41]:
# Eliminemos las columnas que no son útiles para el análisis

columnas_no_utiles = [
    'ProductID',
    'TransactionNumber',
    'CategoryID',
    'ModifyDate',
    'FirstName',
    'MiddleInitial',
    'LastName',
    'CityID',
    'Address',
    'Zipcode',
    'CountryID',
    'CountryCode'
]

df = df.drop(columns=columnas_no_utiles)

In [42]:
df.shape

(6758125, 16)

In [43]:
df.columns

Index(['SalesID', 'SalesPersonID', 'CustomerID', 'Quantity', 'Discount',
       'TotalPrice', 'SalesDate', 'ProductName', 'Price', 'Class', 'Resistant',
       'IsAllergic', 'VitalityDays', 'CityName', 'CountryName',
       'CategoryName'],
      dtype='object')

### Gestion valores nulos

In [44]:
se.porcent_nulos(df)

           nulos%
SalesDate     1.0

In [45]:
# La variable SalesDate presentaba un 1% de valores nulos.
# Al ser clave para el análisis temporal y tener un impacto mínimo, 
# se eliminaron dichas observaciones para mantener la consistencia del análisis.

df = df.dropna(subset=['SalesDate'])

In [46]:
df['SalesDate'].isnull().sum()

np.int64(0)

### Creación de variables nuevas

In [47]:
# Antes de recalcular la columna 'TotalPrice' veamos el rango de columna 'Discount':
df['Discount'].describe()

count    6.690599e+06
mean     2.996458e-02
std      6.397781e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.000000e-01
Name: Discount, dtype: float64

In [48]:
# Recalculamos la columna 'TotalPrice'
df['TotalPrice'] = df['Quantity'] * df['Price'] * (1 - df['Discount'])
df['TotalPrice'] = df['TotalPrice'].round(2)
df['TotalPrice'].describe()

count    6.690599e+06
mean     6.410849e+02
std      5.470784e+02
min      4.000000e-02
25%      1.806500e+02
50%      4.907700e+02
75%      9.837400e+02
max      2.496890e+03
Name: TotalPrice, dtype: float64

In [49]:
# Creamos la columna 'RevenueBruto' que permite analizar el impacto de los descuentos
df['RevenueBruto'] = df['Quantity'] * df['Price']
df['RevenueBruto'] = df['RevenueBruto'].round(2)
df['RevenueBruto'].describe()

count    6.690599e+06
mean     6.608841e+02
std      5.610520e+02
min      4.000000e-02
25%      1.867800e+02
50%      5.073300e+02
75%      1.017350e+03
max      2.496890e+03
Name: RevenueBruto, dtype: float64

In [50]:
# Creamos la columna 'DiscountAmount'
df['DiscountAmount'] = df['RevenueBruto'] - df['TotalPrice']
df['DiscountAmount'] = df['DiscountAmount'].round(2)
df['DiscountAmount'].describe()

count    6.690599e+06
mean     1.979914e+01
std      5.792723e+01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.993800e+02
Name: DiscountAmount, dtype: float64

In [51]:
# Creamos las columnas 'MonthNum', 'Month', 'DayOfWeek' para analisis de ventas temporal

df['MonthNum'] = pd.to_datetime(df['SalesDate']).dt.month
df['Month'] = pd.to_datetime(df['SalesDate']).dt.month_name()
df['DayOfWeek'] = pd.to_datetime(df['SalesDate']).dt.day_name()

In [52]:
df.columns

Index(['SalesID', 'SalesPersonID', 'CustomerID', 'Quantity', 'Discount',
       'TotalPrice', 'SalesDate', 'ProductName', 'Price', 'Class', 'Resistant',
       'IsAllergic', 'VitalityDays', 'CityName', 'CountryName', 'CategoryName',
       'RevenueBruto', 'DiscountAmount', 'MonthNum', 'Month', 'DayOfWeek'],
      dtype='object')

In [53]:
df.shape

(6690599, 21)

In [54]:
# Comprobamos el conjunto de datos final
se.analisis_rapido(df)

Las 5 primeras columnas de Dataframe son:

,SalesID,SalesPersonID,CustomerID,Quantity,Discount,TotalPrice,SalesDate,ProductName,Price,Class,Resistant,IsAllergic,VitalityDays,CityName,CountryName,CategoryName,RevenueBruto,DiscountAmount,MonthNum,Month,DayOfWeek
0,1,6,27039,7,0.0,309.64,2018-02-05 07:38:25.430,Vaccum Bag 10x13,44.2337,High,Unknown,Unknown,41.0,Albuquerque,United States,Confections,309.64,0.00,2,February,Monday
1,2,16,25011,7,0.0,437.82,2018-02-02 16:03:31.150,Sardines,62.5460,Low,Durable,False,90.0,Phoenix,United States,Grain,437.82,0.00,2,February,Friday
2,3,13,94024,24,0.0,1896.44,2018-05-03 19:31:56.880,Crab - Imitation Flakes,79.0184,Medium,Durable,True,0.0,Buffalo,United States,Produce,1896.44,0.00,5,May,Thursday
3,4,8,73966,19,0.2,1236.01,2018-04-07 14:43:55.420,Smirnoff Green Apple Twist,81.3167,High,Durable,True,90.0,Dallas,United States,Seafood,1545.02,309.01,4,April,Saturday
4,5,10,32653,9,0.0,719.80,2018-02-12 15:37:03.940,Coffee - Dark Roast,79.9780,Low,Weak,False,0.0,Charlotte,United States,Poultry,719.80,0.00,2,February,Monday

Información básica de Dataframe:
<class 'pandas.core.frame.DataFrame'>
Index: 6690599 entries, 0 to 6758124
Data columns (total 21 columns):
 #   Column          Dtype
---  ------          -----
 0   SalesID         int64
 1   SalesPersonID   int64
 2   CustomerID      int64
 3   Quantity        int64
 4   Discount        float64
 5   TotalPrice      float64
 6   SalesDate       datetime64[ns]
 7   ProductName     object
 8   Price           float64
 9   Class           object
 10  Resistant       object
 11  IsAllergic      object
 12  VitalityDays    float64
 13  CityName        object
 14  CountryName     object
 15  CategoryName    object
 16  RevenueBruto    float64
 17  DiscountAmount  float64
 18  MonthNum        int32
 19  Month           object
 20  DayOfWeek       object
dtypes: datetime64[ns](1), float64(6), int32(1), int64(4), object(9)
memory usage: 1.1+ GB

None

El número de duplicados es: 0
El número de valores nulos es:

SalesID           0
SalesPersonID     0
CustomerID        0
Quantity          0
Discount          0
TotalPrice        0
SalesDate         0
ProductName       0
Price             0
Class             0
Resistant         0
IsAllergic        0
VitalityDays      0
CityName          0
CountryName       0
CategoryName      0
RevenueBruto      0
DiscountAmount    0
MonthNum          0
Month             0
DayOfWeek         0
dtype: int64

### Guardamos dataset final unido, limpio y transformado:

In [55]:
df.to_csv('../data/processed/sales_final.csv', index=False)